<?php

/**
 * @file
 * Hook implementations.
 */

use \Drupal\little_helpers\Webform\Webform;
use \Drupal\manual_direct_debit\AccountData;
use \Drupal\manual_direct_debit\AccountDataController;

/**
 * Implements hook_payment_method_controller_info().
 */
function manual_direct_debit_payment_method_controller_info() {
  return array('\Drupal\manual_direct_debit\AccountDataController');
}

/**
 * Implements hook_entity_load().
 */
function manual_direct_debit_entity_load(array $entities, $entity_type) {
  if ($entity_type != 'payment') {
    return;
  }
  $query = db_select('manual_direct_debit_account_data', 'd')
    ->fields('d')
    ->condition('pid', array_keys($entities));
  $result = $query->execute();
  while ($data = $result->fetchAssoc()) {
    $payment = $entities[$data['pid']];
    $payment->method_data = array(
      'holder' => $data['holder'],
      'country' => $data['country'],
    ) + unserialize($data['account']);
  }
}

/**
 * Implements hook_ENTITY_TYPE_ACTION().
 */
function manual_direct_debit_payment_insert(Payment $payment) {
  if (!($payment->method->controller instanceof AccountDataController)) {
    return;
  }
  AccountData::fromPayment($payment, TRUE)->save();
}

/**
 * Implements hook_ENTITY_TYPE_ACTION().
 */
function manual_direct_debit_payment_update(Payment $payment) {
  if (!($payment->method->controller instanceof AccountDataController)) {
    return;
  }
  AccountData::fromPayment($payment, FALSE)->save();
}

/**
 * Implements hook_ENTITY_TYPE_ACTION().
 */
function manual_direct_debit_payment_delete(Payment $payment) {
  if (!($payment->method->controller instanceof AccountDataController)) {
    return;
  }
  AccountData::fromPayment($payment, FALSE)->delete();
}

/**
 * Implements hook_webform_results_extra_data().
 *
 * Add extra data to webform submission results.
 *
 * @param stdclass[] $submissions
 *   A list of webform submission objects keyed by their sids.
 * @param stdclass $node
 *   The node object of the webform.
 *
 * @return array[][]
 *   An array of arrays containing extra keyed by sids. Each of those extra
 *   data arrays is an associative array of the form
 *   $data['column_title'] = 'value';
 */
function manual_direct_debit_webform_results_extra_data($submissions, $node) {
  $sids = array_keys($submissions);
  if (empty($sids)) {
    return;
  }

  $extra_data = array();
  $webform = new Webform($node);
  foreach (array_keys($webform->componentsByType('paymethod_select')) as $cid) {
    // Provide at least an empty array for every requested sid.
    $data = array();
    foreach ($sids as $sid) {
      $data[$sid] = array();
    }

    $accounts = AccountData::bySubmissions($node->nid, $cid, $sids);
    foreach ($accounts as $sid => $account) {
      $data[$sid] = array(
        'holder' => $account->holder,
        'iban' => $account->account['iban'],
        'bic' => $account->account['bic'],
        'country' => $account->country,
        'account' => $account->account['account'],
        'bank_code' => $account->account['bank_code'],
      );
    }
    $extra_data[] = $data;
  }
  return $extra_data;
}
