<?php

use \Drupal\little_helpers\Webform\Webform;
use \Drupal\manual_direct_debit\AccountData;

/**
 * Implements hook_payment_method_controller_info().
 */
function manual_direct_debit_payment_method_controller_info() {
  return array('\Drupal\manual_direct_debit\AccountDataController');
}

/**
 * Implements hook_entity_load().
 */
function manual_direct_debit_entity_load(array $entities, $entity_type) {
  if ($entity_type != 'payment')
    return;
  $query = db_select('manual_direct_debit_account_data', 'd')
    ->fields('d')
    ->condition('pid', array_keys($entities));
  $result = $query->execute();
  while ($data = $result->fetchAssoc()) {
    $payment = $entities[$data['pid']];
    $payment->method_data = array(
      'holder' => $data['holder'],
      'country' => $data['country'],
    ) + unserialize($data['account']);
  }
}

function _manual_direct_debit_serialize_account(Payment $payment) {
  $keys = array('iban', 'bic', 'account', 'bank_code');
  $data = array();
  foreach ($keys as $key) {
    $data[$key] = isset($payment->method_data[$key]) ? $payment->method_data[$key] : NULL;
  }
  return serialize($data);
}

/**
 * Implements hook_ENTITY_TYPE_ACTION().
 */
function manual_direct_debit_payment_insert(Payment $payment) {
  if (!($payment->method->controller instanceof \Drupal\manual_direct_debit\AccountDataController))
    return;
  AccountData::fromPayment($payment, TRUE)->save();
}
function manual_direct_debit_payment_update(Payment $payment) {
  if (!($payment->method->controller instanceof \Drupal\manual_direct_debit\AccountDataController))
    return;
  AccountData::fromPayment($payment, FALSE)->save();
}
function manual_direct_debit_payment_delete(Payment $payment) {
  if (!($payment->method->controller instanceof \Drupal\manual_direct_debit\AccountDataController))
    return;
  AccountData::fromPayment($payment, FALSE)->delete();
}

/** 
 * Implements hook_webform_results_extra_data().
 */
function manual_direct_debit_webform_results_extra_data($submissions, $node) {
  $sids = array_keys($submissions);
  if (empty($sids)) {
    return;
  }

  $extra_data = array();
  $webform = new Webform($node);
  foreach (array_keys($webform->componentsByType('paymethod_select')) as $cid) {
    // We need to provide at least an empty array for every requested sid.
    $data = array();
    foreach ($sids as $sid) {
      $data[$sid] = array();
    }

    $accounts = AccountData::bySubmissions($node->nid, $cid, $sids);
    foreach ($accounts as $sid => $account) {
      $data[$sid] = array(
        'holder' => $account->holder,
        'iban' => $account->account['iban'],
        'bic' => $account->account['bic'],
        'country' => $account->country,
        'account' => $account->account['account'],
        'bank_code' => $account->account['bank_code'],
      );
    }
    $extra_data[] = $data;
  }
  return $extra_data;
}
